# Generated by Django 5.0.3 on 2024-03-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slide_image',
            field=models.ImageField(default='', upload_to='slides/'),
        ),
    ]
