# Generated by Django 5.0.3 on 2024-03-21 08:44

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
