# Generated by Django 5.0.3 on 2024-03-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
